#!/usr/bin/env sh
# SPDX-FileCopyrightText: 2022 Severen Redwood <me@severen.dev>
# SPDX-FileCopyrightText: 2022 Keetley Rate <fridgeineyes@gmail.com>
# SPDX-License-Identifier: CC0-1.0

. "$(dirname -- "$0")/_/husky.sh"

reuse lint
pnpm run lint
